version: '3.7'

services:
  begin_anew_core:
    container_name: begin_anew_core_dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      # Allow explicit env var override for tests
      - SMTP_HOST=${SMTP_HOST}
    command: sh start_service.sh
    ports:
      - '3000:3000'
    restart: on-failure
    links:
      - db
    depends_on:
      - db

  db:
      image: postgres:12
      container_name: begin_anew_dev
      environment:
        - POSTGRES_USER=begin_anew
        - POSTGRES_PASSWORD=123123
        - POSTGRES_DB=begin_anew_db
      ports:
        - '5432:5432'
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U begin_anew -d begin_anew_db"]
        interval: 10s
        timeout: 5s
        retries: 5
