"""Initial tables

Revision ID: 586c7729a290
Revises: 
Create Date: 2021-11-16 01:29:07.920019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '586c7729a290'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
